### PR TITLE
Update README.md for env settings

### PR DESCRIPTION
**Pull request by ismogis**
- update a modification in .env files logic to README.md
- minor fixes

Resolves: #12

### CODE REVIEW

**Review by JuhoErvasti — COMMENTED** [review]
Fixes look good.

The .env vs .env.template situation always seemed a bit odd to me. Should the template just be outright deleted if an .env file is included anyway? Not sure it's necessary. Or at least update it to have the same values?

**Comment by ismogis** [comment]
@JuhoErvasti If I understand correctly .env is needed only because of Terraform. Then on the other hand it is a common practice to have .env.template in the repository.

Does @LKajan or @RaineEkman have an opinion?

**Comment by LKajan** [comment]
That's right, currently we have quite clumsy process where Terraform/OpenTofu pulls this repository and invokes `docker compose up` which requires the `.env` file. Therefore the `.env` is needed here in the repo against the best practices. Favorable solution would be that we get rid of the public `.env` here and create one during the infra setup. Probably should set up the infra with OpenTofu and after that pull this repo and configure the .env with Ansible.

In a dreamworld:
1. Fix .env.template to have right variables
2. Remove `.env`
3. Find a way to create `.env` during the cource infra set up

But I'm not sure what to do in the meantime until 3 is resolved.

**Comment by JuhoErvasti** [comment]
Okay! I wasn't aware of that side of it. For my part as far as this PR goes it's okay to merge. Or maybe for now the values from .env should copied over to the template until the Terraform/OpenTofu stuff is resolved?

**Pull request merged**
